version: '3'

services:
  seed:
    image: amazing-orderprocessing:latest
    hostname: seed
    ports:
      - '9110:9110'
    environment:
      CLUSTER_PORT: 4053
      CLUSTER_IP: "seed"
      CLUSTER_SEEDS: "akka.tcp://amazing@seed:4053"

  replica1:
    image: amazing-orderprocessing:latest
    environment:
      CLUSTER_PORT: 4053
      CLUSTER_SEEDS: "akka.tcp://amazing@seed:4053"
    depends_on:
      - "seed"

  replica2:
    image: amazing-orderprocessing:latest
    environment:
      CLUSTER_PORT: 4053
      CLUSTER_SEEDS: "akka.tcp://amazing@seed:4053"
    depends_on:
      - "seed"

  api:
    image: amazing-orderapi:latest
    ports:
      - '8080:80'
    environment:
      CLUSTER_PORT: 4053
      CLUSTER_SEEDS: "akka.tcp://amazing@seed:4053"
    depends_on:
      - "seed"